# REF: https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/
version: '3.7'

services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  nginx:
    build: ./nginx
    ports:
      - 1337:80

  backend:
    build: .
    command: gunicorn waterquality.wsgi:application --bind 0.0.0.0:8000
    container_name: app
    env_file:
      - ./.env
    expose:
      - 8000
    depends_on:
      - redis
      - nginx

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - node-modules:/app/node_modules
    ports:
      - 80:3000
    depends_on:
      - backend
      - nginx

  celery-worker:
    build: .
    command: celery -A waterquality worker -l info
    env_file:
      - ./.env
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A waterquality beat -l info --scheduler djcelery.schedulers.DatabaseScheduler
    env_file:
      - ./.env
    depends_on:
      - redis

  flower:
    image: mher/flower
    env_file:
      - ./.env
    ports:
      - 8888:8888
    depends_on:
      - redis

volumes:
  redis-data:
  node-modules:
