# REF: https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/
version: '3.7'

services:
  web:
    build: .
    #command: gunicorn waterquality.wsgi:application --bind 0.0.0.0:8000 --workers 3
    command: python manage.py runserver 0.0.0.0:8000
    container_name: app
    volumes:
      — .:/app
    ports:
      — 8000:8000
#    env_file:
#      - ./env
#  nginx:
#    build: ./nginx
#    volumes:
#      - static_volume:/home/app/web/staticfiles
#    ports:
#      - 1337:80
#    depends_on:
#      - web
