# REF: https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/
version: '3.7'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: app
    volumes:
    — .:/app
    ports:
    — "8000:8000"
    environment:
      - DEBUG=1
