# REF: https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/
version: '3.7'

services:
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app/backend
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
