# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-01 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, choices=[(b'dc', b'Washington, DC'), (b'nyc', b'New York City'), (b'los', b'Los Angeles'), (b'chicago', b'Chicago'), (b'houston', b'Houston'), (b'phoenix', b'Phoenix')], default='info', max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[(b'info', b'Informational'), (b'boil', b'Boil Water'), (b'notdrink', b'Do Not Drink'), (b'notuse', b'Do Not Use')], default='info', max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=255, null=True)),
                ('geocode', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('keywords', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ignore', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('text', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('text_stopwords', models.TextField(blank=True, default='', null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.location')),
            ],
        ),
        migrations.CreateModel(
            name='url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('tweet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.tweet')),
            ],
        ),
    ]
