# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-13 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='status',
        ),
        migrations.AddField(
            model_name='tweet',
            name='status',
            field=models.CharField(blank=True, choices=[(b'info', b'Informational'), (b'boil', b'Boil Water'), (b'notdrink', b'Do Not Drink'), (b'notuse', b'Do Not Use')], default='info', max_length=255, null=True),
        ),
    ]
