# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-15 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20181213_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violation',
            name='utility',
        ),
        migrations.AddField(
            model_name='location',
            name='geocode',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='utility',
            name='violation',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='violation',
        ),
    ]
