# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-15 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20171215_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
