# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-15 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20181215_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advisory_feed',
            options={'verbose_name': 'Advisory Feed', 'verbose_name_plural': 'Advisory Feeds'},
        ),
        migrations.AlterModelOptions(
            name='advisory_keyword',
            options={'verbose_name': 'Advisory Keyword', 'verbose_name_plural': 'Advisory Keywords'},
        ),
    ]
