# Generated by Django 3.0.2 on 2020-02-11 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_utility_voilation_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisory_feed',
            name='source',
            field=models.CharField(blank=True, choices=[('goog', 'Google News Feed'), ('twitter', 'Twitter'), ('', '')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='advisory_keyword',
            name='source',
            field=models.CharField(blank=True, choices=[('goog', 'Google News Feed'), ('twitter', 'Twitter'), ('', '')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.location'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='source',
            field=models.CharField(blank=True, choices=[('goog', 'Google News Feed'), ('twitter', 'Twitter'), ('', '')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(blank=True, choices=[('info', 'Informational'), ('boil', 'Boil Water'), ('notdrink', 'Do Not Drink'), ('notuse', 'Do Not Use'), ('unknown', 'Unknown'), ('safe', 'Safe')], default='safe', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='county_served',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.location'),
        ),
        migrations.AlterField(
            model_name='county_served',
            name='utility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.utility'),
        ),
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.CharField(blank=True, choices=[('info', 'Informational'), ('boil', 'Boil Water'), ('notdrink', 'Do Not Drink'), ('notuse', 'Do Not Use'), ('unknown', 'Unknown'), ('safe', 'Safe')], default='safe', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.alert'),
        ),
    ]
