# Generated by Django 3.0.2 on 2020-06-23 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200623_0116'),
        ('news', '0009_auto_20200623_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.location'),
        ),
        migrations.AddField(
            model_name='county_served',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.location'),
        ),
    ]
