# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('sourcetype', models.CharField(blank=True, choices=[('weave', 'weave'), ('konekt', 'konekt'), ('sim', 'sim')], max_length=255, null=True)),
                ('devicealias', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('deviceaddress', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('hostip', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('proxy_url', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('type', models.CharField(blank=True, choices=[('conductivity', 'Conductivity'), ('orp', 'Oxygen Reduction Potential'), ('turbitiy', 'turbitiy'), ('temperature', 'temperature'), ('ph', 'Ph')], max_length=255, null=True)),
                ('freq', models.IntegerField(blank=True, default=0, null=True)),
                ('min', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
                ('max', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
                ('amplitude', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
                ('delay', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sim_node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('devicealias', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('sensors', models.ManyToManyField(to='app.sensor')),
            ],
        ),
    ]
