# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-13 09:32
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
                ('metric', models.CharField(blank=True, choices=[(b'conductivity', b'Conductivity'), (b'orp', b'Oxygen Reduction Potential'), (b'odo', b'Dissolved Oxygen'), (b'turbidity', b'Turbidity'), (b'temperature', b'temperature'), (b'ph', b'Ph'), (b'hall', b'Hall Effect Sensor')], default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('position', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('source', models.CharField(blank=True, choices=[(b'usgs', b'usgs')], default='usgs', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.node'),
        ),
    ]
