# Generated by Django 3.0.2 on 2020-03-03 03:40

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('street_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('county', models.CharField(max_length=100, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('state', localflavor.us.models.USStateField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FipsCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips_code', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
                ('fips_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FipsCode')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=255)),
                ('pws_id', models.CharField(max_length=255, unique=True)),
                ('registry_id', models.CharField(max_length=12, unique=True)),
                ('current_violation_score', models.IntegerField(default=0)),
                ('historic_violation_score', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('facility_type', models.CharField(choices=[('CWS', 'Community Water System'), ('OTHER', 'Other')], max_length=255)),
                ('population_served', models.IntegerField(blank=True, default=0, null=True)),
                ('address_key', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Address')),
                ('fips_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FipsCode')),
            ],
        ),
    ]
