# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='offset',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=15),
        ),
    ]
