# Generated by Django 3.0.2 on 2020-03-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200306_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='street_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
