# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sensor_offset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='freq',
        ),
    ]
