# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_sensor_freq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='amplitude',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='max',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='min',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='offset',
        ),
        migrations.AddField(
            model_name='sensor',
            name='mean',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='sensor',
            name='std',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=15),
        ),
    ]
