# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160402_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, choices=[(b'live', b'live'), (b'sim', b'sim')], max_length=255, null=True)),
                ('data', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='commtype',
            field=models.CharField(blank=True, choices=[(b'', b''), (b'weave', b'weave'), (b'konekt', b'konekt')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='sourcetype',
            field=models.CharField(blank=True, choices=[(b'live', b'live'), (b'sim', b'sim')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.node'),
        ),
    ]
