# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-01 02:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181215_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='data',
            name='value',
        ),
        migrations.AddField(
            model_name='data',
            name='metrics',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
