# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160402_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.node')),
            ],
        ),
    ]
