# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-01 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190201_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='score',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='node',
            name='status',
            field=models.CharField(blank=True, choices=[(b'good', b'good')], default='', max_length=255, null=True),
        ),
    ]
