# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='delay',
        ),
    ]
