# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-13 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190702_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='population_served',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
