# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_sensor_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim_node',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
