# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_sim_node_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='created',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='data',
            name='source',
            field=models.CharField(blank=True, choices=[(b'live', b'live'), (b'sim', b'simulator')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='sourcetype',
            field=models.CharField(blank=True, choices=[(b'live', b'live'), (b'sim', b'simulator')], default='sim', max_length=255, null=True),
        ),
    ]
