# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160403_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='data',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='data',
            name='node',
        ),
        migrations.AddField(
            model_name='data',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='data',
            name='long',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='data',
            name='node_alias',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='node_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='sensor_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='sensor_type',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='sensor_units',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='units',
            field=models.CharField(blank=True, choices=[(b'NTU', b'NTU'), (b'mg/L', b'mg/L'), (b'mV', b'mV'), (b'C', b'C'), (b'pH', b'pH'), (b'uS/cm', b'uS/cm')], max_length=255, null=True),
        ),
    ]
