# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-09-24 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata', '0001_initial'),
        ('app', '0009_auto_20190813_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='facilities',
            field=models.ManyToManyField(to='rawdata.EpaFacilitySystem'),
        ),
    ]
