# Generated by Django 3.0.2 on 2020-06-23 01:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_location_facilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='facilities',
        ),
        migrations.AddField(
            model_name='location',
            name='geocode',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.CharField(blank=True, choices=[('info', 'Informational'), ('boil', 'Boil Water'), ('notdrink', 'Do Not Drink'), ('notuse', 'Do Not Use'), ('unknown', 'Unknown'), ('safe', 'Safe')], default='safe', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.location'),
        ),
    ]
