# Generated by Django 3.0.12 on 2021-10-22 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_location_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='quarter',
            field=models.CharField(blank=True, choices=[('q1', 'q1'), ('q2', 'q3'), ('q3', 'q3'), ('q4', 'q4')], default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='year',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
