# Generated by Django 3.0.12 on 2021-11-23 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211022_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='facilities',
        ),
        migrations.AlterField(
            model_name='data',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.location'),
        ),
    ]
