# Generated by Django 3.0.12 on 2022-01-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20211123_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='rank',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
