# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160413_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
