# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-01 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20160413_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='commtype',
            field=models.CharField(blank=True, choices=[(b'', b''), (b'weave', b'weave'), (b'konekt', b'konekt'), (b'redbear', b'RedBear Duo')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(blank=True, choices=[(b'conductivity', b'Conductivity'), (b'orp', b'Oxygen Reduction Potential'), (b'odo', b'Dissolved Oxygen'), (b'turbidity', b'Turbidity'), (b'temperature', b'temperature'), (b'ph', b'Ph'), (b'hall', b'Hall Effect Sensor')], max_length=255, null=True),
        ),
    ]
