# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-04 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpaFacilitySystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacName', models.CharField(max_length=255)),
                ('PWSId', models.CharField(max_length=255, unique=True)),
                ('RegistryID', models.CharField(max_length=12)),
                ('FacStreet', models.CharField(max_length=200)),
                ('FacCity', models.CharField(max_length=100)),
                ('FacState', models.CharField(max_length=2)),
                ('FacZip', models.CharField(max_length=10)),
                ('FacCounty', models.CharField(max_length=100)),
                ('FacFIPSCode', models.CharField(max_length=15)),
                ('FacDerivedZip', models.CharField(max_length=5)),
                ('FacEPARegion', models.CharField(max_length=2)),
                ('FacLat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('FacLong', models.DecimalField(decimal_places=6, max_digits=10)),
                ('FacAccuracyMeters', models.DecimalField(decimal_places=2, max_digits=12)),
                ('FacReferencePoint', models.CharField(max_length=750)),
                ('FacTotalPenalties', models.DecimalField(decimal_places=2, max_digits=12)),
                ('FacDateLastPenalty', models.DateField()),
                ('FacLastPenaltyAmt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('SDWAFormalActionCount', models.IntegerField()),
                ('SDWASystemTypes', models.CharField(max_length=4000)),
                ('FacDerivedStctyFIPS', models.CharField(max_length=5)),
                ('FacPercentMinority', models.DecimalField(decimal_places=2, max_digits=5)),
                ('FacMajorFlag', models.CharField(max_length=1)),
                ('ViolFlag', models.IntegerField()),
                ('CurrVioFlag', models.IntegerField()),
                ('FacPenaltyCount', models.IntegerField()),
                ('FacFormalActionCount', models.IntegerField()),
                ('SDWA3yrComplQtrsHistory', models.CharField(max_length=15)),
                ('SDWAInspections5yr', models.IntegerField()),
                ('SDWAInformalCount', models.IntegerField()),
                ('FacCollectionMethod', models.CharField(max_length=750)),
                ('FacStdCountyName', models.CharField(max_length=300)),
                ('SDWISFlag', models.CharField(max_length=1)),
                ('FacImpWaterFlg', models.CharField(max_length=1)),
                ('Score', models.DecimalField(decimal_places=6, max_digits=12)),
            ],
        ),
    ]
