# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-10-15 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epafacilitysystem',
            name='in_violation',
            field=models.NullBooleanField(),
        ),
    ]
