# Generated by Django 3.0.2 on 2020-02-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata', '0002_epafacilitysystem_in_violation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epafacilitysystem',
            name='FacDerivedStctyFIPS',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='epafacilitysystem',
            name='FacEPARegion',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='epawatersystem',
            name='EPARegion',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='epawatersystem',
            name='FIPSCodes',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
