# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-04 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata', '0002_epafacilitysystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epafacilitysystem',
            name='CurrVioFlag',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='epafacilitysystem',
            name='FacCollectionMethod',
            field=models.CharField(max_length=750, null=True),
        ),
        migrations.AlterField(
            model_name='epafacilitysystem',
            name='FacDateLastPenalty',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='epafacilitysystem',
            name='FacDerivedStctyFIPS',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='epafacilitysystem',
            name='FacDerivedZip',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='epafacilitysystem',
            name='FacFormalActionCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='epafacilitysystem',
            name='FacImpWaterFlg',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='epafacilitysystem',
            name='FacLastPenaltyAmt',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='epafacilitysystem',
            name='FacMajorFlag',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='epafacilitysystem',
            name='FacPenaltyCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='epafacilitysystem',
            name='FacPercentMinority',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='epafacilitysystem',
            name='FacReferencePoint',
            field=models.CharField(max_length=750, null=True),
        ),
        migrations.AlterField(
            model_name='epafacilitysystem',
            name='FacStdCountyName',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='epafacilitysystem',
            name='FacTotalPenalties',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='epafacilitysystem',
            name='RegistryID',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='epafacilitysystem',
            name='SDWA3yrComplQtrsHistory',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='epafacilitysystem',
            name='SDWAFormalActionCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='epafacilitysystem',
            name='SDWAInformalCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='epafacilitysystem',
            name='SDWAInspections5yr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='epafacilitysystem',
            name='SDWASystemTypes',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='epafacilitysystem',
            name='ViolFlag',
            field=models.IntegerField(null=True),
        ),
    ]
