# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-04 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata', '0003_auto_20190604_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epafacilitysystem',
            name='FacLastPenaltyAmt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='epafacilitysystem',
            name='FacTotalPenalties',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
