# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-04 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawdata', '0005_auto_20190604_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epafacilitysystem',
            name='RegistryID',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
